Repository CMU-313/fall23-nodebb-consonants-compadres, pull requests merged in 2023-10, with the labels that each got.

#29 added feature to display account type on user dashboard
  public/src/client/account/edit.js
  public/src/client/topic.js
  public/src/client/topic/votes.js
  src/topics/tags.js
  src/types/tag.ts
  themes/nodebb-theme-persona/library.js
  themes/nodebb-theme-persona/templates/account/profile.tpl
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
  themes/nodebb-theme-persona/templates/recent.tpl
  themes/nodebb-theme-persona/templates/topic.tpl
Labels: enhancement

#31 added backend and front end to classify post as anonymous
  public/openapi/read/topic/topic_id.yaml
  src/topics/create.js
  src/topics/data.js
  src/topics/tags.js
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
Labels: enhancement

#30 hide username on topics for anonymous posts
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: enhancement

#33 [backend] Add endorsement feature
  public/openapi/read/topic/topic_id.yaml
  src/posts/data.js
  src/posts/endorse.js
  src/posts/summary.js
  src/posts/user.js
Labels: enhancement

#36 Added test for anonymous feature to test suite
  test/topics.js
Labels: test

#37 Added documentation to directory
  UserGuide.md
Labels: documentation

#38 added new test to evaluate isAnonymous value
  test/topics.js
Labels: test
